services:
  api:
    build:
      context: ./backend
      dockerfile: ../docker/django/Dockerfile
    command: /start
    volumes:
      - ./backend:/backend
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PG_HOST=postgres-db
      - PG_PORT=5432
    depends_on:
      - postgres-db
    networks:
      - jwt-oauth
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/react/Dockerfile

    container_name: jwt-oauth-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
      - postgres-db
    networks:
      - jwt-oauth

  postgres-db:
    image: postgres:15.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - jwt-oauth
networks:
  jwt-oauth:
    driver: bridge
volumes:
  postgres_data:
  static_volume:
  media_volume:
